///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace teste
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the testeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    [RepositoryFolder("4b605e4c-2b03-43cd-9511-6709aa60878c")]
    public partial class testeRepository : RepoGenBaseFolder
    {
        static testeRepository instance = new testeRepository();

        /// <summary>
        /// Gets the singleton class instance representing the testeRepository element repository.
        /// </summary>
        [RepositoryFolder("4b605e4c-2b03-43cd-9511-6709aa60878c")]
        public static testeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public testeRepository() 
            : base("testeRepository", "/", null, 0, false, "4b605e4c-2b03-43cd-9511-6709aa60878c", ".\\RepositoryImages\\testeRepository4b605e4c.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4b605e4c-2b03-43cd-9511-6709aa60878c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.3.1")]
    public partial class testeRepositoryFolders
    {
    }
#pragma warning restore 0436
}